[package]
name = "teamtailor"
version = "0.1.0"
authors = ["André Ligné <andre@teamtailor.com>"]
edition = "2018"

[dependencies]
clap = "2"
dirs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
